review: review.tex
	pdflatex review
	bibtex review
	pdflatex review
	pdflatex review

ann: annotated_bib.tex
	pdflatex annotated_bib
	bibtex annotated_bib
	pdflatex annotated_bib
	pdflatex annotated_bib
