review: review.tex
	pdflatex review
	bibtex review
	pdflatex review
	pdflatex review

ann: annotated_bib.tex
	pdflatex annotated_bib
	bibtex annotated_bib
	pdflatex annotated_bib
	pdflatex annotated_bib

ann2: ann2.tex
	pdflatex ann2
	bibtex ann2
	pdflatex ann2
	pdflatex ann2

